const STORAGE_KEY='russoTrainerDataV1';
const categoryNames={noun:'Sostantivo',verb:'Verbo',adjective:'Aggettivo',adverb:'Avverbio',pronoun:'Pronome',preposition:'Preposizione'};
const samples=[
{id:crypto.randomUUID(),partOfSpeech:'noun',russian:'молоко́',italian:'latte',pronunciation:'malakò',grammarLabel:'nominativo singolare',notes:'Sostantivo neutro',stats:freshStats()},
{id:crypto.randomUUID(),partOfSpeech:'verb',russian:'чита́ть',italian:'leggere',pronunciation:'čitàt’',grammarLabel:'infinito imperfettivo',notes:'',stats:freshStats()},
{id:crypto.randomUUID(),partOfSpeech:'adverb',russian:'обы́чно',italian:'normalmente, di solito',pronunciation:'abìčna',grammarLabel:'avverbio',notes:'',stats:freshStats()},
{id:crypto.randomUUID(),partOfSpeech:'noun',russian:'хле́ба',italian:'pane',pronunciation:'hlèba',grammarLabel:'genitivo singolare',notes:'Forma di хлеб',stats:freshStats()},
{id:crypto.randomUUID(),partOfSpeech:'verb',russian:'де́лала',italian:'tu facevi / lei faceva',pronunciation:'dièlala',grammarLabel:'passato femminile, imperfettivo',notes:'Forma di делать',stats:freshStats()},
{id:crypto.randomUUID(),partOfSpeech:'pronoun',russian:'она́',italian:'lei',pronunciation:'anà',grammarLabel:'nominativo',notes:'',stats:freshStats()},
{id:crypto.randomUUID(),partOfSpeech:'pronoun',russian:'их',italian:'di loro / loro',pronunciation:'ih',grammarLabel:'genitivo o accusativo',notes:'',stats:freshStats()}
];
let state=loadState();let session=null;let deferredPrompt=null;
function freshStats(){return{attempts:0,correct:0,almost:0,wrong:0,streak:0,lastSeen:null,nextDue:0};}
function loadState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||{entries:[],sessions:[]};}catch{return{entries:[],sessions:[]};}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));renderAll();}
function $(id){return document.getElementById(id);}function escapeHtml(v=''){return v.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}

document.querySelectorAll('.tab').forEach(btn=>btn.addEventListener('click',()=>showView(btn.dataset.view)));
function showView(id){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.view===id));document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===id));renderAll();}

$('entryForm').addEventListener('submit',e=>{e.preventDefault();state.entries.push({id:crypto.randomUUID(),partOfSpeech:$('partOfSpeech').value,russian:$('russian').value.trim(),italian:$('italian').value.trim(),pronunciation:$('pronunciation').value.trim(),grammarLabel:$('grammarLabel').value.trim(),notes:$('notes').value.trim(),stats:freshStats()});e.target.reset();$('formMessage').textContent='Voce salvata.';saveState();setTimeout(()=>$('formMessage').textContent='',2200);});
$('loadSamples').addEventListener('click',()=>{state.entries=samples.map(x=>({...x,id:crypto.randomUUID(),stats:freshStats()}));saveState();});
$('searchVocabulary').addEventListener('input',renderVocabulary);
$('startSession').addEventListener('click',startSession);
$('revealAnswer').addEventListener('click',()=>{$('answerBox').classList.remove('hidden');$('revealAnswer').classList.add('hidden');});
document.querySelectorAll('[data-rating]').forEach(b=>b.addEventListener('click',()=>rateAnswer(b.dataset.rating)));
$('exportData').addEventListener('click',exportData);
$('importData').addEventListener('change',importData);

function buildCards(entries,direction){let cards=[];entries.forEach(entry=>{if(direction==='mixed'||direction==='ru-it')cards.push({entry,direction:'ru-it'});if(direction==='mixed'||direction==='it-ru')cards.push({entry,direction:'it-ru'});});return cards;}
function cardWeight(card){const s=card.entry.stats||freshStats();const overdue=Math.max(0,Date.now()-(s.nextDue||0));return 1+(s.wrong*4)+(s.almost*2)-s.correct+Math.min(8,overdue/86400000);}
function weightedPick(pool){const weights=pool.map(c=>Math.max(.3,cardWeight(c)));let n=Math.random()*weights.reduce((a,b)=>a+b,0);for(let i=0;i<pool.length;i++){n-=weights[i];if(n<=0)return pool[i];}return pool.at(-1);}
function startSession(){let entries=state.entries.filter(e=>$('sessionCategory').value==='all'||e.partOfSpeech===$('sessionCategory').value);if(!entries.length){$('emptyState').classList.remove('hidden');return;}const size=Number($('sessionSize').value);const pool=buildCards(entries,$('sessionDirection').value);const queue=[];for(let i=0;i<size;i++)queue.push(weightedPick(pool));session={queue,index:0,results:[]};$('sessionResult').classList.add('hidden');$('quizArea').classList.remove('hidden');$('emptyState').classList.add('hidden');renderQuestion();}
function renderQuestion(){const card=session.queue[session.index],e=card.entry;const ruToIt=card.direction==='ru-it';$('progressText').textContent=`Domanda ${session.index+1} di ${session.queue.length}`;$('liveScore').textContent=`${session.results.filter(x=>x.rating==='correct').length} corrette`;$('progressBar').style.width=`${session.index/session.queue.length*100}%`;$('questionMeta').textContent=`${categoryNames[e.partOfSpeech]}${e.grammarLabel?' · '+e.grammarLabel:''}`;$('questionText').textContent=ruToIt?e.russian:e.italian;$('questionHint').textContent=ruToIt?e.pronunciation:'Traduci in russo';$('answerText').textContent=ruToIt?e.italian:e.russian;$('answerPronunciation').textContent=ruToIt?'':`Pronuncia: ${e.pronunciation}`;$('answerNotes').textContent=e.notes||'';$('answerBox').classList.add('hidden');$('revealAnswer').classList.remove('hidden');}
function rateAnswer(rating){const card=session.queue[session.index],s=card.entry.stats||freshStats();s.attempts++;s[rating]++;s.lastSeen=Date.now();if(rating==='correct'){s.streak++;const gaps=[1,3,7,14,30,60,90];s.nextDue=Date.now()+86400000*gaps[Math.min(s.streak-1,gaps.length-1)];}else if(rating==='almost'){s.streak=0;s.nextDue=Date.now()+86400000;}else{s.streak=0;s.nextDue=Date.now()+3600000;}card.entry.stats=s;session.results.push({entryId:card.entry.id,rating,direction:card.direction});session.index++;if(session.index>=session.queue.length)finishSession();else renderQuestion();saveState();}
function finishSession(){const total=session.results.length,correct=session.results.filter(x=>x.rating==='correct').length,almost=session.results.filter(x=>x.rating==='almost').length,wrong=total-correct-almost,score=Math.round((correct+almost*.5)/total*100);state.sessions.push({date:Date.now(),total,correct,almost,wrong,score});$('quizArea').classList.add('hidden');$('sessionResult').classList.remove('hidden');$('sessionResult').innerHTML=`<p class="eyebrow">Sessione completata</p><h2>${score}%</h2><p><strong>${correct}</strong> corrette · <strong>${almost}</strong> quasi corrette · <strong>${wrong}</strong> errate</p><button class="primary" onclick="startSession()">Nuova sessione</button>`;saveState();}
function renderVocabulary(){const q=$('searchVocabulary').value.trim().toLowerCase();const items=state.entries.filter(e=>[e.russian,e.italian,e.pronunciation,e.grammarLabel].join(' ').toLowerCase().includes(q));$('vocabularyList').innerHTML=items.length?items.map(e=>`<article class="word-card"><p class="eyebrow">${categoryNames[e.partOfSpeech]}</p><h3>${escapeHtml(e.russian)}</h3><p class="pronunciation">${escapeHtml(e.pronunciation)}</p><p class="translation">${escapeHtml(e.italian)}</p><p>${escapeHtml(e.grammarLabel||'')}</p><footer><span>${e.stats.attempts} tentativi</span><button class="danger" onclick="deleteEntry('${e.id}')">Elimina</button></footer></article>`).join(''):'<div class="panel"><p>Nessuna voce trovata.</p></div>';}
window.deleteEntry=id=>{if(confirm('Eliminare questa voce?')){state.entries=state.entries.filter(e=>e.id!==id);saveState();}};
function renderStats(){const attempts=state.entries.reduce((n,e)=>n+(e.stats?.attempts||0),0),correct=state.entries.reduce((n,e)=>n+(e.stats?.correct||0),0),last=state.sessions.at(-1);$('statsSummary').innerHTML=`<div class="stat"><span>Voci</span><strong>${state.entries.length}</strong></div><div class="stat"><span>Tentativi</span><strong>${attempts}</strong></div><div class="stat"><span>Corrette</span><strong>${attempts?Math.round(correct/attempts*100):0}%</strong></div><div class="stat"><span>Ultima sessione</span><strong>${last?last.score+'%':'—'}</strong></div>`;const weak=[...state.entries].filter(e=>e.stats.attempts).sort((a,b)=>(b.stats.wrong+b.stats.almost)-(a.stats.wrong+a.stats.almost)).slice(0,10);$('weakWords').innerHTML=weak.length?weak.map(e=>`<div class="weak-row"><span><strong>${escapeHtml(e.russian)}</strong> · ${escapeHtml(e.italian)}</span><span>${e.stats.wrong} errori</span></div>`).join(''):'<p>Le statistiche compariranno dopo la prima sessione.</p>';}
function renderAll(){$('emptyState').classList.toggle('hidden',state.entries.length>0);renderVocabulary();renderStats();}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`russo-trainer-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);}
function importData(ev){const file=ev.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const imported=JSON.parse(reader.result);if(!Array.isArray(imported.entries))throw new Error();state=imported;saveState();alert('Backup importato.');}catch{alert('File non valido.');}};reader.readAsText(file);}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').classList.remove('hidden');});$('installBtn').addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('installBtn').classList.add('hidden');});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
renderAll();